# Generated by Django 6.0.7 on 2026-08-05 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_classification', to='games.game')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_editorial_classifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['game__name', 'game__id'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro_score', models.PositiveSmallIntegerField(help_text='Challenge Micro score — moment-to-moment skill demands.', verbose_name='Challenge Micro')),
                ('mystiko_score', models.PositiveSmallIntegerField(help_text='Challenge Mystiko score — depth, knowledge, and discovery.', verbose_name='Challenge Mystiko')),
                ('macro_score', models.PositiveSmallIntegerField(help_text='Challenge Macro score — strategic and long-term demands.', verbose_name='Challenge Macro')),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_profile', to='classifications.editorialclassification')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('micro_score__gte', 0), ('micro_score__lte', 100), ('mystiko_score__gte', 0), ('mystiko_score__lte', 100), ('macro_score__gte', 0), ('macro_score__lte', 100)), name='challenge_scores_range_ck')],
            },
        ),
        migrations.CreateModel(
            name='RewardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro_score', models.PositiveSmallIntegerField(help_text='Reward Micro score — immediate feedback and pacing.', verbose_name='Reward Micro')),
                ('mystiko_score', models.PositiveSmallIntegerField(help_text='Reward Mystiko score — discovery-based satisfaction.', verbose_name='Reward Mystiko')),
                ('macro_score', models.PositiveSmallIntegerField(help_text='Reward Macro score — long-term progression and achievement.', verbose_name='Reward Macro')),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_profile', to='classifications.editorialclassification')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('micro_score__gte', 0), ('micro_score__lte', 100), ('mystiko_score__gte', 0), ('mystiko_score__lte', 100), ('macro_score__gte', 0), ('macro_score__lte', 100)), name='reward_scores_range_ck')],
            },
        ),
    ]
