# Generated by Django 6.0.7 on 2026-08-16 10:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('classifications', '0001_initial'),
        ('games', '0007_alter_game_developer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialGroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_community_leader', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='editorialclassification',
            options={'ordering': ['game__name', 'game__id'], 'verbose_name': 'Editorial classification submission', 'verbose_name_plural': 'Editorial classification submissions'},
        ),
        migrations.AddField(
            model_name='editorialclassification',
            name='submitted_base_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=3),
        ),
        migrations.AddField(
            model_name='editorialclassification',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_editorial_classifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorialclassification',
            name='submitted_role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('moderator', 'Moderator'), ('community_leader', 'Community Leader'), ('community', 'Community')], default='community', max_length=32),
        ),
        migrations.AlterField(
            model_name='editorialclassification',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_classification', to='games.game'),
        ),
        migrations.AddConstraint(
            model_name='editorialclassification',
            constraint=models.UniqueConstraint(fields=('game', 'submitted_by'), name='editorial_submission_game_user_uniq'),
        ),
        migrations.AddField(
            model_name='editorialgroupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_profile', to='auth.group'),
        ),
        migrations.AddConstraint(
            model_name='editorialgroupprofile',
            constraint=models.CheckConstraint(condition=models.Q(('is_community_leader', True), ('is_moderator', True), _negated=True), name='editorial_group_role_exclusive_ck'),
        ),
    ]
