# Generated by Django 6.0.7 on 2026-08-16 15:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0004_alter_editorialclassification_submitted_by'),
        ('games', '0007_alter_game_developer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='editorialclassification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('submitted_base_weight', Decimal('1.00')), ('submitted_role', 'superuser')), models.Q(('submitted_base_weight', Decimal('0.95')), ('submitted_role', 'moderator')), models.Q(('submitted_base_weight', Decimal('0.65')), ('submitted_role', 'community_leader')), models.Q(('submitted_base_weight', Decimal('0.20')), ('submitted_role', 'community')), _connector='OR'), name='editorial_submission_role_weight_ck'),
        ),
    ]
