# Generated by Django 6.0.7 on 2026-08-17 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0005_editorialclassification_editorial_submission_role_weight_ck'),
        ('games', '0007_alter_game_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationEpoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch_id', models.CharField(max_length=64, unique=True)),
                ('cutoff_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('master_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial')], default='running', max_length=16)),
                ('games_attempted', models.PositiveIntegerField(default=0)),
                ('games_succeeded', models.PositiveIntegerField(default=0)),
                ('games_failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-cutoff_at'],
            },
        ),
        migrations.CreateModel(
            name='BoundaryCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_version', models.CharField(max_length=64)),
                ('status', models.CharField(blank=True, max_length=48)),
                ('delta', models.FloatField(default=0.0)),
                ('calibration_population_hash', models.CharField(blank=True, max_length=64)),
                ('population_size', models.PositiveIntegerField(default=0)),
                ('subset_count_attempted', models.PositiveIntegerField(default=0)),
                ('subset_count_ready', models.PositiveIntegerField(default=0)),
                ('sampler_version', models.CharField(blank=True, max_length=64)),
                ('seed_or_stream', models.CharField(blank=True, max_length=256)),
                ('calibrated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_calibrations', to='games.game')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'master_version'), name='boundary_calibration_game_version_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CalculationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16)),
                ('failure_category', models.CharField(blank=True, max_length=48)),
                ('error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_attempts', to='games.game')),
                ('epoch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='classifications.calculationepoch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'epoch', 'attempt_number'), name='calculation_attempt_game_epoch_number_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ClassificationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=48)),
                ('input_population_hash', models.CharField(blank=True, max_length=64)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('validated_count', models.PositiveIntegerField(default=0)),
                ('cutoff_at', models.DateTimeField()),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('master_version', models.CharField(blank=True, max_length=64)),
                ('methods_version', models.CharField(blank=True, max_length=64)),
                ('bhpcm_version', models.CharField(blank=True, max_length=64)),
                ('confidence_final_version', models.CharField(blank=True, max_length=64)),
                ('method_1_status', models.CharField(blank=True, max_length=48)),
                ('method_2_status', models.CharField(blank=True, max_length=48)),
                ('method_3_status', models.CharField(blank=True, max_length=48)),
                ('method_1_raw_challenge', models.JSONField(blank=True, null=True)),
                ('method_1_raw_reward', models.JSONField(blank=True, null=True)),
                ('method_1_integer_challenge', models.JSONField(blank=True, null=True)),
                ('method_1_integer_reward', models.JSONField(blank=True, null=True)),
                ('method_2_raw_challenge', models.JSONField(blank=True, null=True)),
                ('method_2_raw_reward', models.JSONField(blank=True, null=True)),
                ('method_2_integer_challenge', models.JSONField(blank=True, null=True)),
                ('method_2_integer_reward', models.JSONField(blank=True, null=True)),
                ('method_3_raw_challenge', models.JSONField(blank=True, null=True)),
                ('method_3_raw_reward', models.JSONField(blank=True, null=True)),
                ('method_3_integer_challenge', models.JSONField(blank=True, null=True)),
                ('method_3_integer_reward', models.JSONField(blank=True, null=True)),
                ('unified_raw_challenge', models.JSONField(blank=True, null=True)),
                ('unified_raw_reward', models.JSONField(blank=True, null=True)),
                ('unified_integer_challenge', models.JSONField(blank=True, null=True)),
                ('unified_integer_reward', models.JSONField(blank=True, null=True)),
                ('confidence_final', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('confidence_label', models.CharField(blank=True, max_length=16)),
                ('confidence_provenance', models.JSONField(blank=True, default=dict)),
                ('conflict_classification', models.CharField(blank=True, max_length=32)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(default=False)),
                ('became_current_at', models.DateTimeField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('failure_category', models.CharField(blank=True, max_length=48)),
                ('error_summary', models.TextField(blank=True)),
                ('epoch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='classifications.calculationepoch')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_snapshots', to='games.game')),
            ],
            options={
                'ordering': ['game__id', '-calculated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('game',), name='classification_snapshot_single_current_uniq')],
            },
        ),
    ]
