# Generated by Django 6.0.8 on 2026-09-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0006_calculationepoch_boundarycalibration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationattempt',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16),
        ),
    ]
