# Generated by Django 6.0.8 on 2026-09-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0007_alter_calculationattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationepoch',
            name='games_skipped_unchanged',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
