# Generated by Django 6.0.8 on 2026-09-09 14:19

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0008_calculationepoch_games_skipped_unchanged"),
        ("games", "0015_delete_errorregistryentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGameScoreSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge_micro",
                    models.PositiveSmallIntegerField(
                        help_text="Challenge Micro score — moment-to-moment skill demands.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "challenge_mystiko",
                    models.PositiveSmallIntegerField(
                        help_text="Challenge Mystiko score — depth, knowledge, and discovery.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "challenge_macro",
                    models.PositiveSmallIntegerField(
                        help_text="Challenge Macro score — strategic and long-term demands.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "reward_micro",
                    models.PositiveSmallIntegerField(
                        help_text="Reward Micro score — moment-to-moment satisfaction.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "reward_mystiko",
                    models.PositiveSmallIntegerField(
                        help_text="Reward Mystiko score — intellectual satisfaction.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "reward_macro",
                    models.PositiveSmallIntegerField(
                        help_text="Reward Macro score — long-form satisfaction.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp of original submission (anchors the 15-day window).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of most recent in-place supersession update.",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game being classified.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_submissions",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Community user who submitted this classification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "classifications_user_game_score_submission",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "game", "-created_at"],
                        name="idx_user_game_created",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("challenge_micro__gte", 0),
                            ("challenge_micro__lte", 100),
                            ("challenge_mystiko__gte", 0),
                            ("challenge_mystiko__lte", 100),
                            ("challenge_macro__gte", 0),
                            ("challenge_macro__lte", 100),
                            (
                                "challenge_micro",
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.Value(100),
                                        "-",
                                        models.F("challenge_mystiko"),
                                    ),
                                    "-",
                                    models.F("challenge_macro"),
                                ),
                            ),
                        ),
                        name="community_challenge_scores_total_100_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reward_micro__gte", 0),
                            ("reward_micro__lte", 100),
                            ("reward_mystiko__gte", 0),
                            ("reward_mystiko__lte", 100),
                            ("reward_macro__gte", 0),
                            ("reward_macro__lte", 100),
                            (
                                "reward_micro",
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.Value(100),
                                        "-",
                                        models.F("reward_mystiko"),
                                    ),
                                    "-",
                                    models.F("reward_macro"),
                                ),
                            ),
                        ),
                        name="community_reward_scores_total_100_ck",
                    ),
                ],
            },
        ),
    ]
