# Generated by Django 6.0.8 on 2026-09-10 04:35

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0009_usergamescoresubmission'),
        ('games', '0016_game_aesthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamescoresubmission',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual Modal Submission'), ('QUESTIONNAIRE', 'Questionnaire Generated')], db_index=True, default='MANUAL', help_text='How this community submission was generated.', max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionnaireResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v1.0.0', help_text='Questionnaire registry version used.', max_length=16)),
                ('dominant_aesthetic', models.CharField(max_length=32)),
                ('secondary_aesthetic', models.CharField(blank=True, max_length=32, null=True)),
                ('is_true_aesthetic', models.BooleanField(default=False)),
                ('answers', models.JSONField(help_text='Full map of question ID to chosen answer option ID.')),
                ('q15_rating', models.PositiveSmallIntegerField(help_text='Relevance rating from 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('raw_challenge_micro', models.PositiveIntegerField()),
                ('raw_challenge_macro', models.PositiveIntegerField()),
                ('raw_challenge_mystiko', models.PositiveIntegerField()),
                ('raw_reward_micro', models.PositiveIntegerField()),
                ('raw_reward_macro', models.PositiveIntegerField()),
                ('raw_reward_mystiko', models.PositiveIntegerField()),
                ('normalized_challenge_micro', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('normalized_challenge_macro', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('normalized_challenge_mystiko', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('normalized_reward_micro', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('normalized_reward_macro', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('normalized_reward_mystiko', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('adjusted_challenge_micro', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('adjusted_challenge_macro', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('adjusted_challenge_mystiko', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('adjusted_reward_micro', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('adjusted_reward_macro', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('adjusted_reward_mystiko', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('game', models.ForeignKey(help_text='Canonical game evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_results', to='games.game')),
                ('user', models.ForeignKey(help_text='User who completed the questionnaire.', on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classifications_questionnaire_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE_IN_CALCULATION', 'Active in Calculation'), ('SUPERSEDED_BY_MANUAL', 'Superseded by Manual Submission'), ('ARCHIVED_KEPT_MANUAL', 'Archived (User Chose Manual)'), ('STAFF_EDITORIAL_ROUTED', 'Staff Submission Routed to Editorial')], db_index=True, default='ACTIVE_IN_CALCULATION', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_classifications', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_classifications', to=settings.AUTH_USER_MODEL)),
                ('latest_result', models.OneToOneField(help_text='Most recent completed questionnaire result.', on_delete=django.db.models.deletion.CASCADE, related_name='active_classification', to='classifications.questionnaireresult')),
            ],
            options={
                'db_table': 'classifications_questionnaire_classification',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='usergamescoresubmission',
            name='questionnaire_result',
            field=models.ForeignKey(blank=True, help_text='Questionnaire attempt that generated this score, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_submissions', to='classifications.questionnaireresult'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_challenge_micro', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(100), '-', models.F('normalized_challenge_macro')), '-', models.F('normalized_challenge_mystiko')))), name='chk_qresult_norm_challenge_sum_100'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_reward_micro', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(100), '-', models.F('normalized_reward_macro')), '-', models.F('normalized_reward_mystiko')))), name='chk_qresult_norm_reward_sum_100'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_challenge_micro', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(100), '-', models.F('adjusted_challenge_macro')), '-', models.F('adjusted_challenge_mystiko')))), name='chk_qresult_adj_challenge_sum_100'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_reward_micro', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(100), '-', models.F('adjusted_reward_macro')), '-', models.F('adjusted_reward_mystiko')))), name='chk_qresult_adj_reward_sum_100'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireclassification',
            unique_together={('user', 'game')},
        ),
    ]
