# Generated by Django 6.0.8 on 2026-09-10 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0010_usergamescoresubmission_source_questionnaireresult_and_more'),
        ('games', '0016_game_aesthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaireclassification',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='questionnaireclassification',
            index=models.Index(fields=['status', '-updated_at'], name='idx_qclass_status_updated'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresult',
            index=models.Index(fields=['user', 'game', '-created_at'], name='idx_qresult_user_game_created'),
        ),
        migrations.AddIndex(
            model_name='usergamescoresubmission',
            index=models.Index(fields=['source', 'game'], name='idx_usergamescoresub_source'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireclassification',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='uniq_qclass_user_game'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('q15_rating__gte', 1), ('q15_rating__lte', 10)), name='chk_qresult_q15_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_challenge_micro__lte', 100)), name='chk_qresult_norm_c_micro_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_challenge_macro__lte', 100)), name='chk_qresult_norm_c_macro_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_challenge_mystiko__lte', 100)), name='chk_qresult_norm_c_mystiko_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_reward_micro__lte', 100)), name='chk_qresult_norm_r_micro_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_reward_macro__lte', 100)), name='chk_qresult_norm_r_macro_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_reward_mystiko__lte', 100)), name='chk_qresult_norm_r_mystiko_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_challenge_micro__lte', 100)), name='chk_qresult_adj_c_micro_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_challenge_macro__lte', 100)), name='chk_qresult_adj_c_macro_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_challenge_mystiko__lte', 100)), name='chk_qresult_adj_c_mystiko_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_reward_micro__lte', 100)), name='chk_qresult_adj_r_micro_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_reward_macro__lte', 100)), name='chk_qresult_adj_r_macro_range'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresult',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_reward_mystiko__lte', 100)), name='chk_qresult_adj_r_mystiko_range'),
        ),
    ]
