# Generated by Django 6.0.8 on 2026-09-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0011_questionnaire_db_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialclassification',
            name='aesthetic',
            field=models.CharField(blank=True, choices=[('SENSORY', 'Sensory Pleasure'), ('FANTASY', 'Fantasy Pleasure'), ('NARRATIVE', 'Narrative Pleasure'), ('CHALLENGE', 'Challenge Pleasure')], db_index=True, help_text='Primary aesthetic driver identified by editorial review. The four options: SENSORY = audiovisual, action, and visceral thrills; FANTASY = escapism, exploration, and building; NARRATIVE = story, characters, and lore; CHALLENGE = difficulty, mastery, and competition.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usergamescoresubmission',
            name='aesthetic',
            field=models.CharField(blank=True, choices=[('SENSORY', 'Sensory Pleasure'), ('FANTASY', 'Fantasy Pleasure'), ('NARRATIVE', 'Narrative Pleasure'), ('CHALLENGE', 'Challenge Pleasure')], db_index=True, help_text='Primary aesthetic selected by the community submitter. The four options: SENSORY = audiovisual, action, and visceral thrills; FANTASY = escapism, exploration, and building; NARRATIVE = story, characters, and lore; CHALLENGE = difficulty, mastery, and competition.', max_length=20, null=True),
        ),
    ]
