# Generated by Django 6.0.8 on 2026-09-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0012_editorialclassification_aesthetic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialclassification',
            name='secondary_aesthetic',
            field=models.CharField(blank=True, choices=[('SENSORY', 'Sensory Pleasure'), ('FANTASY', 'Fantasy Pleasure'), ('NARRATIVE', 'Narrative Pleasure'), ('CHALLENGE', 'Challenge Pleasure')], db_index=True, help_text='Optional secondary aesthetic driver identified by editorial review; NULL when there is no meaningful second aesthetic.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usergamescoresubmission',
            name='secondary_aesthetic',
            field=models.CharField(blank=True, choices=[('SENSORY', 'Sensory Pleasure'), ('FANTASY', 'Fantasy Pleasure'), ('NARRATIVE', 'Narrative Pleasure'), ('CHALLENGE', 'Challenge Pleasure')], db_index=True, help_text='Optional secondary aesthetic selected by the community submitter; NULL when none was chosen.', max_length=20, null=True),
        ),
    ]
