# Generated by Django 6.0.7 on 2026-08-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('steam', 'Steam'), ('manual', 'Manual')], max_length=16)),
                ('external_id', models.CharField(blank=True, help_text='Steam App ID (decimal) — required for Steam, must be NULL for manual.', max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL-safe identifier. Not regenerated on name changes.', max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('game', 'Game'), ('dlc', 'Downloadable content'), ('demo', 'Demo'), ('other', 'Other')], default='game', max_length=16)),
                ('listing_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('manual_description', models.TextField(blank=True)),
                ('manual_image_url', models.URLField(blank=True, max_length=500)),
                ('manual_website_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['listing_status', 'name', 'id'], name='game_listing_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('external_id__isnull', False), ('source_type', 'steam'), models.Q(('external_id', ''), _negated=True)), models.Q(('external_id__isnull', True), ('source_type', 'manual')), _connector='OR'), name='game_source_external_id_ck'), models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_type', 'external_id'), name='game_unique_source_external_id')],
            },
        ),
    ]
