# Generated by Django 6.0.7 on 2026-08-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='content_type',
            field=models.CharField(choices=[('game', 'Game'), ('dlc', 'Downloadable content'), ('demo', 'Demo'), ('software', 'Software'), ('soundtrack', 'Soundtrack'), ('unknown', 'Unknown')], default='game', max_length=16),
        ),
    ]
