# Generated by Django 6.0.7 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_migrate_other_to_unknown"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="steam_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text=(
                    "Steam header-image URL persisted from import candidates "
                    "(SBGC-55).  Never populated from manual/editorial data; "
                    "use manual_image_url for manual records."
                ),
                max_length=500,
            ),
            preserve_default=False,
        ),
    ]
