# Generated by Django 6.0.7 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_steam_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="last_steam_refresh_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When this Steam record's metadata was last successfully "
                    "verified against Steam (SBGC-56).  NULL = never refreshed.  "
                    "Not set when the Steam app is unavailable."
                ),
                null=True,
            ),
        ),
    ]
