# Generated by Django 6.0.7 on 2026-08-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_last_steam_refresh_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, help_text='Manual developer name (SBGC-59).  Owned by manual/editorial data; never populated from Steam and never changed by Steam refresh.', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, help_text='Manual release date (SBGC-59).  Owned by manual/editorial data; never populated from Steam and never changed by Steam refresh.', null=True),
        ),
    ]
