# Generated by Django 6.0.7 on 2026-08-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_developer_game_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, help_text='Developer name for manually managed game metadata.', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_steam_refresh_at',
            field=models.DateTimeField(blank=True, help_text="When this Steam record's metadata was last successfully verified against Steam.  NULL = never refreshed.  Not set when the Steam app is unavailable.", null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, help_text='Release date for manually managed game metadata. Accepted formats: YYYY-MM-DD, DD-MM-YYYY, DD/MM/YYYY, or YYYY/MM/DD.', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='steam_image_url',
            field=models.URLField(blank=True, help_text='Steam header-image URL persisted from import data.  Never populated from manual/editorial data; use manual_image_url for manual records.', max_length=500),
        ),
    ]
