# Generated by Django 6.0.7 on 2026-08-21 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamRefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('alert_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='steam_refresh_run_single_active_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SteamRefreshGameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('unavailable', 'Unavailable'), ('failed', 'Failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steam_refresh_attempts', to='games.game')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.steamrefreshrun')),
            ],
            options={
                'ordering': ['attempt_number', 'game_id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'game', 'attempt_number'), name='steam_refresh_attempt_run_game_num_uniq')],
            },
        ),
    ]
