# Generated by Django 6.0.7 on 2026-08-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_steamrefreshrun_steamrefreshgameattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='library_capsule_url',
            field=models.URLField(blank=True, help_text='Steam Library Capsule (portrait key-art) image URL for the layered Game-detail presentation.  Steam-owned and derived from the App ID for base Games; blank for manual and non-game Steam content.', max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='library_hero_url',
            field=models.URLField(blank=True, help_text='Steam Library Hero image URL for the layered Game-detail presentation.  Steam-owned and derived from the App ID for base Games; blank for manual and non-game Steam content.', max_length=500),
        ),
    ]
