# Generated by Django 6.0.7 on 2026-08-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_game_library_capsule_url_game_library_hero_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="manual_description",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Short description. Steam-managed for Steam Games unless "
                    "overridden in Admin; manually editable for Manual Games."
                ),
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="description_overridden",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True = description is human-owned; Steam refresh preserves "
                    "it. False = Steam-managed (Steam Games only)."
                ),
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="developer_overridden",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True = developer is human-owned; Steam refresh preserves "
                    "it. False = Steam-managed (Steam Games only)."
                ),
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="release_date_overridden",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True = release date is human-owned; Steam refresh preserves "
                    "it. False = Steam-managed (Steam Games only)."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="developer",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Developer name. Steam-managed for Steam Games unless "
                    "overridden in Admin; manually editable for Manual Games."
                ),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateField(
                blank=True,
                help_text=(
                    "Release date. Steam-managed for Steam Games unless "
                    "overridden in Admin; manually editable for Manual Games. "
                    "Accepted formats: YYYY-MM-DD, DD-MM-YYYY, DD/MM/YYYY, or "
                    "YYYY/MM/DD."
                ),
                null=True,
            ),
        ),
    ]
