# Generated by Django 6.0.7 on 2026-08-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_backfill_steam_override_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='manual_capsule_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='manual_hero_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
