# Generated by Django 6.0.7 on 2026-08-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_content_type_overridden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Error Registry',
                'verbose_name_plural': 'Error Registry',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
