# Generated by Django 6.0.8 on 2026-09-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_errorregistryentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorRegistryEntry',
        ),
    ]
