# Generated by Django 6.0.8 on 2026-09-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0015_delete_errorregistryentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="aesthetic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SENSORY", "Sensory"),
                    ("FANTASY", "Fantasy"),
                    ("NARRATIVE", "Narrative"),
                    ("CHALLENGE", "Challenge"),
                ],
                db_index=True,
                help_text="Canonical primary aesthetic category resolved from the SBGC-171 questionnaire.  NULL = not yet resolved.",
                max_length=20,
                null=True,
            ),
        ),
    ]
