# Generated by Django 6.0.8 on 2026-09-11 03:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_game_aesthetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='similarity_calculated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the most recent similarity score generation for this game.', null=True),
        ),
        migrations.CreateModel(
            name='GameSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Final similarity percentage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('source_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_destinations', to='games.game')),
                ('target_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_sources', to='games.game')),
            ],
            options={
                'db_table': 'games_game_similarity',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['source_game', '-score'], name='idx_gamesim_src_score')],
                'unique_together': {('source_game', 'target_game')},
            },
        ),
    ]
