# Generated by Django 6.0.8 on 2026-09-06 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_date', models.DateField(blank=True, help_text='Latest distinct calendar date the user authenticated.', null=True)),
                ('daily_login_count', models.PositiveIntegerField(default=0, help_text='Total distinct daily logins accumulated by this user.')),
                ('is_dormant_superuser', models.BooleanField(default=False, help_text='True if an environment-designated superuser was demoted due to inactivity.')),
                ('is_temporary_superuser', models.BooleanField(default=False, help_text='True if a moderator was temporarily promoted to cover an inactive superuser.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User security profile',
                'verbose_name_plural': 'User security profiles',
                'db_table': 'auth_user_security_profile',
            },
        ),
    ]
