# Generated by Django 6.0.8 on 2026-09-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tech Stack Registry',
                'verbose_name_plural': 'Tech Stack Registry',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ErrorRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Error Registry',
                'verbose_name_plural': 'Error Registry',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
