# Generated by Django 6.0.8 on 2026-09-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencyregistryentry',
            options={'default_permissions': ('view',), 'managed': False, 'verbose_name': 'Tech Stack Registry', 'verbose_name_plural': 'Tech Stack Registry'},
        ),
        migrations.AlterModelOptions(
            name='errorregistryentry',
            options={'default_permissions': ('view',), 'managed': False, 'verbose_name': 'Error Registry', 'verbose_name_plural': 'Error Registry'},
        ),
    ]
