# Generated by Django 6.0.8 on 2026-09-12 05:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_dependencyregistryentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAccountDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email_snapshot', models.EmailField(help_text='Retained email to notify the offender upon ban execution.', max_length=254)),
                ('offending_username_snapshot', models.CharField(max_length=150)),
                ('ban_reason', models.CharField(max_length=250)),
                ('scheduled_for', models.DateTimeField(db_index=True, help_text='Exact timestamp when the hard purge runs (T + 3 hours).')),
                ('executed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_scheduled_account_deletion',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_username', models.BooleanField(default=False)),
                ('reason_name', models.BooleanField(default=False)),
                ('reason_bio', models.BooleanField(default=False)),
                ('reason_other', models.BooleanField(default=False)),
                ('other_description', models.CharField(blank=True, default='', help_text="Plain text description if 'Other' was selected.", max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('pending_username_change', 'Pending Username Change'), ('pending_bio_change', 'Pending First Name / Last Name / Bio Change'), ('scheduled_for_deletion', 'Scheduled for Permanent Ban / Account Deletion'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending_review', max_length=48)),
                ('possible_brigading', models.BooleanField(db_index=True, default=False, help_text='System-flagged when a sudden spike in reports occurs.')),
                ('repeat_offender_at_submission', models.BooleanField(default=False, help_text='Snapshot flag indicating whether the offender had prior non-pending reports.')),
                ('action_reason', models.CharField(blank=True, default='', help_text='Reason logged by staff when taking punitive action.', max_length=250)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('offending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_user_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['offending_user', 'status'], name='idx_report_offender_status'), models.Index(fields=['created_at', 'offending_user'], name='idx_report_brigade_scan')],
            },
        ),
    ]
