#!/usr/bin/env python3
"""Update the generated context-sources section of skills.md.

Reads the canonical context.md and the archived prior context to produce a
self-contained generated block inside skills.md.  The block is delimited by
HTML comments so the script can safely rewrite it on every invocation.
"""

import hashlib
import sys
from pathlib import Path

BEGIN_MARKER = "<!-- BEGIN GENERATED CONTEXT SOURCES -->"
END_MARKER = "<!-- END GENERATED CONTEXT SOURCES -->"


def repo_root() -> Path:
    """Resolve the repository root from this script's location."""
    return Path(__file__).resolve().parent.parent


def ensure_markers(text: str) -> str:
    """Return *text* unchanged if markers exist; otherwise insert them at the
    end of section 2 (Mandatory source-of-truth order) — right before the
    ``---`` that precedes section 3."""
    if BEGIN_MARKER in text and END_MARKER in text:
        return text

    # Insert after the last line of section 2 (the MUST-NOT paragraph) and
    # before the HR + section-3 heading.
    anchor = (
        "A coding agent MUST NOT claim that work is complete when "
        "implementation differs from `context.md` without recording "
        "the deviation."
    )
    idx = text.find(anchor)
    if idx == -1:
        sys.exit(
            "ERROR: Could not locate the section-2 anchor sentence in "
            "skills.md.  Has the file been significantly restructured?"
        )

    # Jump to the end of the line containing the anchor.
    end_of_line = text.index("\n", idx)
    insertion_point = end_of_line + 1

    generated_block = (
        f"\n{BEGIN_MARKER}\n"
        "<!-- This section is auto-generated by scripts/update-skills-context.py. -->\n"
        "<!-- Do not edit manually. -->\n"
        f"{END_MARKER}\n"
    )
    return text[:insertion_point] + generated_block + text[insertion_point:]


def generated_content(context_hash: str, archive_hash: str) -> str:
    """Return the generated block body (without surrounding markers)."""
    return f"""This section is **auto-generated** by `scripts/update-skills-context.py`.
**Do not edit manually.**  Run `npm run update:skills-context` to refresh.

## Context documents

| Document                                                | Role               | SHA-256 (first 12 hex) |
| ------------------------------------------------------- | ------------------ | ---------------------- |
| `context.md`                                            | **Canonical**      | `{context_hash}`       |
| `docs/archive/context-pre-reward-framework-2026-07-22.md` | Historical archive | `{archive_hash}`       |

## Mandatory reading rules

1. `context.md` is the **authoritative project baseline**.  Every agent
   MUST read it before implementing, reviewing, or modifying any part of
   the repository.
2. The archived context (`docs/archive/context-pre-reward-framework-2026-07-22.md`)
   is **historical reference only**.  It represents the state of the project
   before the dual-profile (Challenge / Reward) framework was introduced.
   Consult it only for historical investigation — it MUST NOT override or
   contradict the current `context.md`.
3. The canonical framework now contains **separate Challenge and Reward
   profiles**, each scored on **Micro**, **Mystiko**, and **Macro**
   dimensions.  The two profiles are related but remain conceptually and
   numerically independent.
"""


def sha12(path: Path) -> str:
    """Return the first 12 hex chars of the file's SHA-256."""
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12]


def main() -> None:
    root = repo_root()
    context_path = root / "context.md"
    archive_path = root / "docs" / "archive" / "context-pre-reward-framework-2026-07-22.md"
    skills_path = root / "skills.md"

    for p in (context_path, archive_path):
        if not p.is_file():
            sys.exit(f"ERROR: Required file not found: {p}")

    skills_text = skills_path.read_text(encoding="utf-8")
    skills_text = ensure_markers(skills_text)

    context_hash = sha12(context_path)
    archive_hash = sha12(archive_path)
    body = generated_content(context_hash, archive_hash)

    # Locate the markers and replace everything between them.
    start = skills_text.index(BEGIN_MARKER) + len(BEGIN_MARKER)
    end = skills_text.index(END_MARKER, start)

    # Handle any trailing newline that follows the start marker.
    if skills_text[start] == "\n":
        start += 1

    new_skills = skills_text[:start] + body + "\n" + skills_text[end:]
    skills_path.write_text(new_skills, encoding="utf-8")
    print("skills.md updated.")


if __name__ == "__main__":
    main()
