# Generated by Django 6.0.8 on 2026-09-09 08:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0015_delete_errorregistryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, default='', help_text='Public profile bio (max 250 characters).', max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('avatar_key', models.CharField(default='male_1', help_text='Key identifier of the pre-rendered avatar asset.', max_length=64)),
                ('border_type', models.CharField(choices=[('NONE', 'None'), ('PRESET', 'Custom Preset Border'), ('SOLID', 'Solid Color Border')], default='NONE', max_length=10)),
                ('border_preset_id', models.PositiveSmallIntegerField(blank=True, help_text='Border preset index (1 through 5).', null=True)),
                ('border_color', models.CharField(blank=True, default='', help_text='Hex color code for solid color border (e.g. #00FFCC).', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Must be a valid 6-digit hex color code.')])),
                ('steam_id', models.CharField(blank=True, default='', help_text='Linked 64-bit Steam Community ID.', max_length=64)),
                ('steam_profile_url', models.URLField(blank=True, default='', help_text='Public URL to Steam community profile.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserTopGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='Order rank from 1 to 5.')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_games', to='users.userprofile')),
            ],
            options={
                'db_table': 'auth_user_top_game',
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'rank'), name='unique_profile_game_rank'), models.UniqueConstraint(fields=('profile', 'game'), name='unique_profile_game_entry')],
            },
        ),
    ]
