# Generated by Django 6.0.8 on 2026-09-09 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio_mode',
            field=models.CharField(choices=[('PLAIN', 'Plain Text Mode'), ('BBCODE', 'Advanced BBCode Mode')], default='PLAIN', help_text='Formatting engine used to parse and render the bio.', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', help_text='Public profile bio (max 500 raw characters; 250 visible).', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
