# Generated by Django 6.0.8 on 2026-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio_mode_and_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopgame',
            name='rank',
            field=models.PositiveSmallIntegerField(help_text='Order rank from 1 to 6.'),
        ),
    ]
